### ISSUE TITLE
PDO??

### ISSUE THREAD

**Issue by ehzawad** [abrarShariar/crud#1]
PDO is better for database integration in PHP.. And It is more object oriented...Should we try?

**Comment by abrarShariar** [comment]
I have always used MySQLi for db driver in CI (kind of default for me). In CI most of the database functionalities are handled by CI's own functions. So, its kind of under-the-hood stuff that remains quite abstract. 

I think it wont matter much except a few syntax changes

**Comment by ehzawad** [comment]
All right..

**Comment by abrarShariar** [comment]
But we can of course try PDO as long as we have someone comfortable with it
