### ISSUE TITLE
Application_Controller_Path(Routes)

### ISSUE THREAD

**Issue by ehzawad** [abrarShariar/crud#2]
The index.php is loading just fine..But when I hit submit button or Create/blog that results in 404 not found. File permission is assigned perfectly. May be relative path issues.

Is there any way that CI can dynamically change the routes according to LAMP folder mapping...

My folder structure ../vhosts/crud/  (My Apache vhosts directories)
I have another folder l../ocalhost/public/crud(My LAMP directory)

Both attempts failed...

Here need to mention that may I need to configure alternatively for LAMP ../htdocs/crud/
(My machine Ubuntu 14.04.3 LTS)

![hell](https://cloud.githubusercontent.com/assets/12381692/13560062/2978b292-e3e9-11e5-927c-eae466d3c51d.png)
![jharvard](https://cloud.githubusercontent.com/assets/12381692/13560064/2cc743dc-e3e9-11e5-88e0-7470479d8293.png)

**Comment by abrarShariar** [comment]
Change the folder name to **crud** (if you havent yet)

Please make sure you have changed the `$config['base_url']` found in line:26 of _\application\config\config.php_ . It  should look like :

`$config['base_url'] = 'http://localhost/crud/demo';`

**Comment by ehzawad** [comment]
Folder name already **crud** and line:26 as like as you have said

**Comment by abrarShariar** [comment]
As most of the **stackoverflow**  Q/A suggests, one of the main reason to get this error 
is the code for **mod_rewrite** in the **.htaccess**  file (where we rewrite the code and remove index.php from the default path). Try changing the code to this: 

```
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php/$0 [PT,L]
</IfModule>
```

**NOTE:**  I think the **mod_rewrite** in .htaccess has some variation with Xampp, for Lampp

More Reference: [htaccess-not-working-on-localhost-lampp-ubuntu](http://stackoverflow.com/questions/24700283/htaccess-not-working-on-localhost-lampp-ubuntu)

**Comment by ehzawad** [comment]
http://localhost/crud/demo/main/create
http://localhost/crud/demo/main/new_data
_404 not found_

Where is **main**/create (class/method) located??

Maybe, **_CI_Controller_** cannot able to get proper path

**Comment by abrarShariar** [comment]
the **mod_rewrite** has some difference in Lampp (please check my previous comment)

All the controller methods are located :`/application/controllers/Main.php`
The _create()_ method at line: 23 and the _new_data()_ method at line: 29

**Comment by ehzawad** [comment]
Already...checked and changed .htaccess file but still not working....

**Comment by SohanChy** [comment]
After almost two hours of frustration, I have finally gotten it to work on LAMP.
It was just due to lamp being too much over secure :p

Before using this on LAMP,
Go to terminal and:
`sudo a2enmod rewrite` 
`sudo gedit /etc/apache2/sites-available/default`
and add/modify it to

```
 <Directory /var/www/>  
            Options Indexes FollowSymLinks MultiViews  
            # changed from None to FileInfo       
            AllowOverride FileInfo  
            Order allow,deny  
            allow from all  
    </Directory>
```

Then finally `sudo gedit /etc/apache2/apache2.conf`
and change 

```
<Directory /var/www/>    
    Options Indexes FollowSymLinks  
    AllowOverride NONE  
    Require all granted  
</Directory>
```

to 

```
<Directory /var/www/>  
    Options Indexes FollowSymLinks  
    AllowOverride ALL  
    Require all granted  
</Directory>
```

@abrarShariar @ehzShelter

**Comment by abrarShariar** [comment]
Congratulations @SohanChy :+1:
